---
# Helion Stackato Console UI (stratos)

resources:

  # versioning
  - name: resource-version
    type: semver
    source:
      driver: git
      initial_version: 0.0.1
      uri: git@github.com:hpcloud/stratos-deploy.git
      branch: version
      file: version
      private_key: {{github-psrivate-key}}

  # git repos
  - name: helion-ui-theme
    type: git
    source:
      uri: git@github.com:hpcloud/helion-ui-theme.git
      branch: master
      private_key: {{github-private-key}}
  - name: helion-ui-framework
    type: git
    source:
      uri: git@github.com:hpcloud/helion-ui-framework.git
      branch: master
      private_key: {{github-private-key}}
  - name: stratos-ui
    type: git
    source:
      uri: git@github.com:hpcloud/stratos-ui.git
      branch: concourse
      private_key: {{github-private-key}}
  - name: portal-proxy
    type: git
    source:
      uri: git@github.com:hpcloud/portal-proxy.git
      branch: concourse
      private_key: {{github-private-key}}

  # docker images
  - name: stratos-server-image
    type: docker-image
    source:
      repository: docker-registry.helion.space:443/helioncf/stratos-server
  - name: portal-proxy-image
    type: docker-image
    source:
      repository: docker-registry.helion.space:443/helioncf/portal-proxy

  # deployment
  - name: stratos-deploy
    type: git
    source:
      uri: git@github.com:hpcloud/stratos-deploy.git
      branch: concourse
      private_key: {{github-private-key}}

  # HSM assets
  
jobs:
  - name: build-console
    serial: true
    plan:

    # Get the git resources
    - get: stratos-deploy
    - get: portal-proxy
    - get: helion-ui-theme
    - get: helion-ui-framework
    - get: stratos-ui

    # Get the current version, bump it
    - get: resource-version
      params: {bump: patch}
    - put: resource-version
      params: {file: resource-version/number}

    # - task: build-proxy-image
    #   file: stratos-deploy/ci/tasks/build-proxy-image.yml
    # - put: portal-proxy-image
    #   params:
    #     dockerfile: portal-proxy-output/Dockerfile.UCP
    #     build: portal-proxy-output

    # - task: build-ui-image
    #   file: stratos-deploy/ci/tasks/build-ui-image.yml
    # - put: stratos-server-image
    #   params:
    #     dockerfile: stratos-server-output/Dockerfile.UCP
    #     build: stratos-server-output

    - task: build-hsm-configs
      file: stratos-deploy/ci/tasks/build-hsm-configs.yml
      params:
        registry: {{registry}}
        tag: {{ [resource-version/number] }}

    # TODO (wchrisjohnson): How should I handle the filename here? Currently
    #      throwing an error on download; upload works fine.
  
